### ISSUE TITLE
How do NGOs' projects appear in devtracker?

### ISSUE THREAD

**Issue by anjesh** [DFID/devtracker-from-api#215]
How does devtracker pull project information from other projects. Does the organisation have to mention GB-1 as funding organisation to activities to appear in devtracker? Or are there other requirements as well. Thanks.

For e.g. https://devtracker.dfid.gov.uk/projects/GB-CHC-250456-GPAF-IMP-086 from "Find your Feet"

**Comment by g-shafiullah** [comment]
Hi Anjesh,

Your assumption is correct.

You need to publish GB-1 as funding organisation in your activity details.

And then you need to publish the data in IATI.

DevTracker will pull out the data based on that logic.

Thanks

Gazi
BSD
DFID Ext:2113007
Cell:+8801817181411

**Comment by g-shafiullah** [comment]
Hi Anjesh,

Please ignore my previous reply.

I have provided you wrong information.

Basically you just need to put participating-activity-id=' GB-GOV-1' in the incoming funds transaction.

Note: now we are GB-GOV-1 not GB-1 anymore.

Thanks

Gazi
BSD
DFID Ext:2113007
Cell:+8801817181411

From: Gazi Shafiullah
Sent: 08 February 2017 16:52
To: 'DFID/devtracker-from-api'
Subject: RE: [DFID/devtracker-from-api] How do NGOs' projects appear in devtracker? (#215)

Hi Anjesh,

Your assumption is correct.

You need to publish GB-1 as funding organisation in your activity details.

And then you need to publish the data in IATI.

DevTracker will pull out the data based on that logic.

Thanks

Gazi
BSD
DFID Ext:2113007
Cell:+8801817181411

**Comment by anjesh** [comment]
Do you mean provider-org/@ref = "GB-GOV-1" or provider-org/@provider-activity-id?
http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/transaction/provider-org/

If provider-org/@provider-activity-id, then NGOs will need to find DFID activity-id and put it in their transaction.

**Comment by johnadamsDFID** [comment]
Hi Anjesh

In order to make the links correctly in DevTracker and for other traceability initiatives, you need to do two things:

1. **participating-org**: Make sure that you reference the organisation that directly funded your activity in the  `participating-org/@role=funding` element.

2. **incoming funds**: Reference the funding activity by its iati-identifier in the incoming funds transaction, using `provider-org/provider-activity-id`. This is the **key thing** needed to make the link in DevTracker.

If the organisation is not directly funded by DFID, then you should make reference to the **next activity up the chain** and ensure that all activities further up the chain are similarly marked up.

We will write up and post further instructions on this in the wiki.

John

**Comment by johnadamsDFID** [comment]
Hi Anjesh

Yes, it needs to be provider-activity-id as that is the only way of linking to a funding activity.

John

**Comment by anjesh** [comment]
Thanks John. Wiki would be very helpful.
